# Generated by Django 5.2.11 on 2026-02-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=1433)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('databases', models.TextField(help_text='Bases de données reliées, séparées par une virgule')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
