# Generated by Django 5.2.11 on 2026-02-24 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_donnees', models.CharField(max_length=100)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('nombre_tables', models.IntegerField()),
                ('total_lignes', models.IntegerField()),
                ('total_null', models.IntegerField()),
                ('total_doublons', models.IntegerField()),
                ('total_anomalies', models.IntegerField()),
                ('score_qualite', models.FloatField()),
                ('serveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
            ],
            options={
                'ordering': ['-date_analyse'],
            },
        ),
    ]
