# Generated by Django 5.2.11 on 2026-03-07 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_donnees', models.CharField(max_length=100)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('nb_tables', models.IntegerField(default=0)),
                ('tables_sans_pk', models.IntegerField(default=0)),
                ('tables_sans_index', models.IntegerField(default=0)),
                ('tables_jamais_utilisees', models.IntegerField(default=0)),
                ('serveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
            ],
            options={
                'ordering': ['-date_analyse'],
            },
        ),
        migrations.CreateModel(
            name='AnalyseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_donnees', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=200)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('a_pk', models.BooleanField(default=False)),
                ('a_index', models.BooleanField(default=False)),
                ('jamais_utilisee', models.BooleanField(default=False)),
                ('nb_fk', models.IntegerField(default=0)),
                ('nb_check', models.IntegerField(default=0)),
                ('nb_colonnes', models.IntegerField(default=0)),
                ('nb_nullables', models.IntegerField(default=0)),
                ('nb_doublons', models.IntegerField(default=0)),
                ('derniere_modification', models.DateTimeField(blank=True, null=True)),
                ('taille_mb', models.FloatField(default=0)),
                ('nb_lignes', models.IntegerField(default=0)),
                ('nb_procedures', models.IntegerField(default=0)),
                ('nb_vues', models.IntegerField(default=0)),
                ('serveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
            ],
            options={
                'ordering': ['-date_analyse', 'base_donnees', 'table_name'],
            },
        ),
        migrations.DeleteModel(
            name='AnalyseResultat',
        ),
    ]
