# Generated by Django 5.2.11 on 2026-03-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_analysebase_analysetable_delete_analyseresultat'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysebase',
            name='nb_fk_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysebase',
            name='nb_procedures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysebase',
            name='nb_vues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysebase',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='analysetable',
            name='derniere_procedure',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
