# Generated by Django 5.2.11 on 2026-04-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0003_analysebase_nb_fk_total_analysebase_nb_procedures_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMResponseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("model_name", models.CharField(max_length=100)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "latency_ms",
                    models.FloatField(
                        help_text="Temps de réponse du modèle en millisecondes"
                    ),
                ),
            ],
        ),
    ]
